
var __cov_aWgJdwQVhNHZHShX16SdtQ = (Function('return this'))();
if (!__cov_aWgJdwQVhNHZHShX16SdtQ.__coverage__) { __cov_aWgJdwQVhNHZHShX16SdtQ.__coverage__ = {}; }
__cov_aWgJdwQVhNHZHShX16SdtQ = __cov_aWgJdwQVhNHZHShX16SdtQ.__coverage__;
if (!(__cov_aWgJdwQVhNHZHShX16SdtQ['example/js/apple.js'])) {
   __cov_aWgJdwQVhNHZHShX16SdtQ['example/js/apple.js'] = {"path":"example/js/apple.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":12},"end":{"line":1,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":9,"column":1}},"2":{"start":{"line":2,"column":4},"end":{"line":2,"column":22}},"3":{"start":{"line":4,"column":4},"end":{"line":4,"column":36}},"4":{"start":{"line":6,"column":4},"end":{"line":6,"column":40}},"5":{"start":{"line":8,"column":4},"end":{"line":8,"column":16}}},"branchMap":{"1":{"line":2,"type":"binary-expr","locations":[{"start":{"line":2,"column":11},"end":{"line":2,"column":15}},{"start":{"line":2,"column":19},"end":{"line":2,"column":21}}]},"2":{"line":4,"type":"binary-expr","locations":[{"start":{"line":4,"column":16},"end":{"line":4,"column":25}},{"start":{"line":4,"column":29},"end":{"line":4,"column":35}}]},"3":{"line":6,"type":"binary-expr","locations":[{"start":{"line":6,"column":17},"end":{"line":6,"column":27}},{"start":{"line":6,"column":31},"end":{"line":6,"column":39}}]}}};
}
__cov_aWgJdwQVhNHZHShX16SdtQ = __cov_aWgJdwQVhNHZHShX16SdtQ['example/js/apple.js'];
__cov_aWgJdwQVhNHZHShX16SdtQ.s['1']++;var Apple=function(opts){__cov_aWgJdwQVhNHZHShX16SdtQ.f['1']++;__cov_aWgJdwQVhNHZHShX16SdtQ.s['2']++;opts=(__cov_aWgJdwQVhNHZHShX16SdtQ.b['1'][0]++,opts)||(__cov_aWgJdwQVhNHZHShX16SdtQ.b['1'][1]++,{});__cov_aWgJdwQVhNHZHShX16SdtQ.s['3']++;this.name=(__cov_aWgJdwQVhNHZHShX16SdtQ.b['2'][0]++,opts.name)||(__cov_aWgJdwQVhNHZHShX16SdtQ.b['2'][1]++,'Fuji');__cov_aWgJdwQVhNHZHShX16SdtQ.s['4']++;this.sound=(__cov_aWgJdwQVhNHZHShX16SdtQ.b['3'][0]++,opts.sound)||(__cov_aWgJdwQVhNHZHShX16SdtQ.b['3'][1]++,'crunch');__cov_aWgJdwQVhNHZHShX16SdtQ.s['5']++;return this;};
