
var __cov_uv1ynfRDXQDTNzQBJWry8g = (Function('return this'))();
if (!__cov_uv1ynfRDXQDTNzQBJWry8g.__coverage__) { __cov_uv1ynfRDXQDTNzQBJWry8g.__coverage__ = {}; }
__cov_uv1ynfRDXQDTNzQBJWry8g = __cov_uv1ynfRDXQDTNzQBJWry8g.__coverage__;
if (!(__cov_uv1ynfRDXQDTNzQBJWry8g['example/js/wombat.js'])) {
   __cov_uv1ynfRDXQDTNzQBJWry8g['example/js/wombat.js'] = {"path":"example/js/wombat.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0]},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":13},"end":{"line":1,"column":28}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":15},"end":{"line":7,"column":30}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":14,"column":2}},"2":{"start":{"line":2,"column":4},"end":{"line":2,"column":36}},"3":{"start":{"line":3,"column":4},"end":{"line":3,"column":22}},"4":{"start":{"line":5,"column":4},"end":{"line":5,"column":37}},"5":{"start":{"line":7,"column":4},"end":{"line":11,"column":5}},"6":{"start":{"line":8,"column":8},"end":{"line":8,"column":37}},"7":{"start":{"line":8,"column":19},"end":{"line":8,"column":37}},"8":{"start":{"line":10,"column":8},"end":{"line":10,"column":25}},"9":{"start":{"line":13,"column":4},"end":{"line":13,"column":16}}},"branchMap":{"1":{"line":3,"type":"binary-expr","locations":[{"start":{"line":3,"column":11},"end":{"line":3,"column":15}},{"start":{"line":3,"column":19},"end":{"line":3,"column":21}}]},"2":{"line":5,"type":"binary-expr","locations":[{"start":{"line":5,"column":16},"end":{"line":5,"column":25}},{"start":{"line":5,"column":29},"end":{"line":5,"column":36}}]},"3":{"line":8,"type":"if","locations":[{"start":{"line":8,"column":8},"end":{"line":8,"column":8}},{"start":{"line":8,"column":8},"end":{"line":8,"column":8}}]}}};
}
__cov_uv1ynfRDXQDTNzQBJWry8g = __cov_uv1ynfRDXQDTNzQBJWry8g['example/js/wombat.js'];
__cov_uv1ynfRDXQDTNzQBJWry8g.s['1']++;var Wombat=function(opts){__cov_uv1ynfRDXQDTNzQBJWry8g.f['1']++;__cov_uv1ynfRDXQDTNzQBJWry8g.s['2']++;console.log('Log option works');__cov_uv1ynfRDXQDTNzQBJWry8g.s['3']++;opts=(__cov_uv1ynfRDXQDTNzQBJWry8g.b['1'][0]++,opts)||(__cov_uv1ynfRDXQDTNzQBJWry8g.b['1'][1]++,{});__cov_uv1ynfRDXQDTNzQBJWry8g.s['4']++;this.name=(__cov_uv1ynfRDXQDTNzQBJWry8g.b['2'][0]++,opts.name)||(__cov_uv1ynfRDXQDTNzQBJWry8g.b['2'][1]++,'Wally');__cov_uv1ynfRDXQDTNzQBJWry8g.s['5']++;this.eat=function(food){__cov_uv1ynfRDXQDTNzQBJWry8g.f['2']++;__cov_uv1ynfRDXQDTNzQBJWry8g.s['6']++;if(!food){__cov_uv1ynfRDXQDTNzQBJWry8g.b['3'][0]++;__cov_uv1ynfRDXQDTNzQBJWry8g.s['7']++;throw Error('D:');}else{__cov_uv1ynfRDXQDTNzQBJWry8g.b['3'][1]++;}__cov_uv1ynfRDXQDTNzQBJWry8g.s['8']++;return'nom nom';};__cov_uv1ynfRDXQDTNzQBJWry8g.s['9']++;return this;};
